"""
SEC EDGAR + US 거래소 데이터로 ticker_names.py 자동 생성
한국어 이름 있는 종목은 한국어, 없는 종목은 영문 회사명 사용
"""
import requests
import re
import os

# ── 1. SEC EDGAR 전체 티커 + 회사명 ──────────────────────────────
print("SEC EDGAR 데이터 수집 중...")
r = requests.get(
    "https://www.sec.gov/files/company_tickers.json",
    headers={"User-Agent": "FinSwipe swj0718820@gmail.com"},
    timeout=30,
)
sec_data = r.json()
sec_map = {}
for item in sec_data.values():
    t = item["ticker"].upper().strip()
    name = item["title"].strip()
    # 전부 대문자면 Title Case로 변환
    if name == name.upper():
        name = name.title()
    # 백슬래시 제거
    name = name.replace("\\", "")
    sec_map[t] = name
print(f"  SEC 티커 수: {len(sec_map)}")

# ── 2. 현재 거래소 상장 티커 (NYSE + NASDAQ + AMEX) ───────────────
print("거래소 티커 목록 수집 중...")
r2 = requests.get(
    "https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/all/all_tickers.txt",
    timeout=30,
)
valid_tickers = set(r2.text.strip().split("\n"))
print(f"  유효 US 티커 수: {len(valid_tickers)}")

# ── 3. 기존 한국어 이름 매핑 ─────────────────────────────────────
KO_MAP = {
    "AAPL": {"corp": "Apple Inc.", "ko": "애플"},
    "MSFT": {"corp": "Microsoft Corp.", "ko": "마이크로소프트"},
    "GOOGL": {"corp": "Alphabet Inc. (A)", "ko": "알파벳 A"},
    "GOOG": {"corp": "Alphabet Inc. (C)", "ko": "알파벳 C"},
    "AMZN": {"corp": "Amazon.com Inc.", "ko": "아마존닷컴"},
    "META": {"corp": "Meta Platforms Inc.", "ko": "메타"},
    "TSLA": {"corp": "Tesla Inc.", "ko": "테슬라"},
    "NVDA": {"corp": "NVIDIA Corp.", "ko": "엔비디아"},
    "NFLX": {"corp": "Netflix Inc.", "ko": "넷플릭스"},
    "ORCL": {"corp": "Oracle Corp.", "ko": "오라클"},
    "CRM": {"corp": "Salesforce Inc.", "ko": "세일즈포스"},
    "NOW": {"corp": "ServiceNow Inc.", "ko": "서비스나우"},
    "ADBE": {"corp": "Adobe Inc.", "ko": "어도비 시스템즈"},
    "CSCO": {"corp": "Cisco Systems Inc.", "ko": "시스코 시스템즈"},
    "ACN": {"corp": "Accenture plc", "ko": "액센츄어"},
    "CTSH": {"corp": "Cognizant Technology Solutions", "ko": "코그니전트"},
    "INTU": {"corp": "Intuit Inc.", "ko": "인튜이트"},
    "ADP": {"corp": "Automatic Data Processing", "ko": "오토매틱 데이터 프로세싱"},
    "ADSK": {"corp": "Autodesk Inc.", "ko": "오토데스크"},
    "ANSS": {"corp": "ANSYS Inc.", "ko": "앤시스"},
    "EPAM": {"corp": "EPAM Systems Inc.", "ko": "EPAM 시스템즈"},
    "GDDY": {"corp": "GoDaddy Inc.", "ko": "고대디"},
    "GEN": {"corp": "Gen Digital Inc.", "ko": "Gen 디지털"},
    "FFIV": {"corp": "F5 Inc.", "ko": "F5 네트웍스"},
    "AKAM": {"corp": "Akamai Technologies", "ko": "아카마이"},
    "VRSN": {"corp": "VeriSign Inc.", "ko": "베리사인"},
    "DELL": {"corp": "Dell Technologies", "ko": "델 테크놀로지"},
    "HPQ": {"corp": "HP Inc.", "ko": "HP"},
    "HPE": {"corp": "Hewlett Packard Enterprise", "ko": "휴렛팩커드 엔터프라이즈"},
    "NTAP": {"corp": "NetApp Inc.", "ko": "넷앱"},
    "WDC": {"corp": "Western Digital Corp.", "ko": "웨스턴 디지털"},
    "STX": {"corp": "Seagate Technology", "ko": "씨게이트"},
    "INTC": {"corp": "Intel Corp.", "ko": "인텔"},
    "AMD": {"corp": "Advanced Micro Devices", "ko": "AMD"},
    "AVGO": {"corp": "Broadcom Inc.", "ko": "브로드컴"},
    "QCOM": {"corp": "Qualcomm Inc.", "ko": "퀄컴"},
    "TXN": {"corp": "Texas Instruments", "ko": "텍사스인스트루먼트"},
    "MU": {"corp": "Micron Technology", "ko": "마이크론 테크놀로지"},
    "AMAT": {"corp": "Applied Materials", "ko": "어플라이드 머티어리얼즈"},
    "LRCX": {"corp": "Lam Research Corp.", "ko": "램리서치"},
    "KLAC": {"corp": "KLA Corp.", "ko": "KLA Corp."},
    "ASML": {"corp": "ASML Holding", "ko": "ASML"},
    "TSM": {"corp": "Taiwan Semiconductor", "ko": "TSMC"},
    "ADI": {"corp": "Analog Devices Inc.", "ko": "아나로그디바이스"},
    "MCHP": {"corp": "Microchip Technology", "ko": "마이크로칩 테크"},
    "NXPI": {"corp": "NXP Semiconductors", "ko": "NXP세미컨덕터즈"},
    "ON": {"corp": "ON Semiconductor", "ko": "온 세미컨덕터"},
    "SWKS": {"corp": "Skyworks Solutions", "ko": "스카이웍스 솔루션즈"},
    "QRVO": {"corp": "Qorvo Inc.", "ko": "코르보"},
    "MPWR": {"corp": "Monolithic Power Systems", "ko": "모놀리틱 파워"},
    "MRVL": {"corp": "Marvell Technology", "ko": "마벨 테크놀로지"},
    "SMCI": {"corp": "Super Micro Computer", "ko": "슈퍼마이크로"},
    "ARM": {"corp": "Arm Holdings", "ko": "ARM 홀딩스"},
    "TER": {"corp": "Teradyne Inc.", "ko": "테라다인"},
    "ENTG": {"corp": "Entegris Inc.", "ko": "엔테그리스"},
    "ONTO": {"corp": "Onto Innovation", "ko": "온토 이노베이션"},
    "ACLS": {"corp": "Axcelis Technologies", "ko": "액셀리스 테크놀로지"},
    "WOLF": {"corp": "Wolfspeed Inc.", "ko": "울프스피드"},
    "PLTR": {"corp": "Palantir Technologies", "ko": "팔란티어 테크"},
    "AI": {"corp": "C3.ai Inc.", "ko": "C3.ai"},
    "SOUN": {"corp": "SoundHound AI", "ko": "사운드하운드 AI"},
    "PATH": {"corp": "UiPath Inc.", "ko": "유아이패스"},
    "BBAI": {"corp": "BigBear.ai Holdings", "ko": "빅베어 AI"},
    "CRWD": {"corp": "CrowdStrike Holdings", "ko": "크라우드스트라이크"},
    "PANW": {"corp": "Palo Alto Networks", "ko": "팔로 알토 네트웍스"},
    "FTNT": {"corp": "Fortinet Inc.", "ko": "포티넷"},
    "ZS": {"corp": "Zscaler Inc.", "ko": "즈스케일러"},
    "S": {"corp": "SentinelOne Inc.", "ko": "센티넬원"},
    "OKTA": {"corp": "Okta Inc.", "ko": "옥타"},
    "SNOW": {"corp": "Snowflake Inc.", "ko": "스노우플레이크"},
    "DDOG": {"corp": "Datadog Inc.", "ko": "데이터도그"},
    "MDB": {"corp": "MongoDB Inc.", "ko": "몽고DB"},
    "NET": {"corp": "Cloudflare Inc.", "ko": "클라우드플레어"},
    "TWLO": {"corp": "Twilio Inc.", "ko": "트윌리오"},
    "ZM": {"corp": "Zoom Video Communications", "ko": "줌"},
    "SHOP": {"corp": "Shopify Inc.", "ko": "쇼피파이"},
    "WDAY": {"corp": "Workday Inc.", "ko": "워크데이"},
    "HUBS": {"corp": "HubSpot Inc.", "ko": "허브스팟"},
    "CFLT": {"corp": "Confluent Inc.", "ko": "컨플루언트"},
    "GTLB": {"corp": "GitLab Inc.", "ko": "깃랩"},
    "FROG": {"corp": "JFrog Ltd.", "ko": "제이프로그"},
    "ESTC": {"corp": "Elastic N.V.", "ko": "엘라스틱"},
    "BRZE": {"corp": "Braze Inc.", "ko": "브레이즈"},
    "PAYC": {"corp": "Paycom Software", "ko": "페이컴"},
    "PAYX": {"corp": "Paychex Inc.", "ko": "페이첵스"},
    "IT": {"corp": "Gartner Inc.", "ko": "가트너"},
    "ROP": {"corp": "Roper Technologies", "ko": "로퍼 테크놀로지"},
    "PTC": {"corp": "PTC Inc.", "ko": "PTC"},
    "SNPS": {"corp": "Synopsys Inc.", "ko": "시놉시스"},
    "CDNS": {"corp": "Cadence Design Systems", "ko": "케이던스 디자인 시스템"},
    "TYL": {"corp": "Tyler Technologies", "ko": "타일러 테크놀로지"},
    "TRMB": {"corp": "Trimble Inc.", "ko": "트림블"},
    "VRSK": {"corp": "Verisk Analytics", "ko": "베리스크 어낼리틱스"},
    "MSCI": {"corp": "MSCI Inc.", "ko": "MSCI"},
    "FDS": {"corp": "FactSet Research Systems", "ko": "팩트셋 리서치 시스템"},
    "BR": {"corp": "Broadridge Financial Solutions", "ko": "브로드리지"},
    "JKHY": {"corp": "Jack Henry & Associates", "ko": "잭 헨리 앤 어소시에이츠"},
    "FISV": {"corp": "Fiserv Inc.", "ko": "파이서브"},
    "FIS": {"corp": "Fidelity National Information", "ko": "FIS"},
    "GPN": {"corp": "Global Payments Inc.", "ko": "글로벌 페이먼트"},
    "DIS": {"corp": "The Walt Disney Co.", "ko": "월트 디즈니"},
    "CMCSA": {"corp": "Comcast Corp.", "ko": "컴캐스트"},
    "WBD": {"corp": "Warner Bros. Discovery", "ko": "워너 브라더스 디스커버리"},
    "PARA": {"corp": "Paramount Global", "ko": "파라마운트"},
    "SPOT": {"corp": "Spotify Technology", "ko": "스포티파이"},
    "FOXA": {"corp": "Fox Corp. (A)", "ko": "폭스 코퍼레이션"},
    "FOX": {"corp": "Fox Corp. (B)", "ko": "폭스 B"},
    "NWS": {"corp": "News Corp.", "ko": "뉴스 코퍼레이션"},
    "LYV": {"corp": "Live Nation Entertainment", "ko": "라이브 네이션"},
    "MTCH": {"corp": "Match Group", "ko": "매치 그룹"},
    "RDDT": {"corp": "Reddit Inc.", "ko": "레딧"},
    "PINS": {"corp": "Pinterest Inc.", "ko": "핀터레스트"},
    "SNAP": {"corp": "Snap Inc.", "ko": "스냅"},
    "BMBL": {"corp": "Bumble Inc.", "ko": "범블"},
    "EA": {"corp": "Electronic Arts", "ko": "일렉트로닉 아츠"},
    "TTWO": {"corp": "Take-Two Interactive", "ko": "테이크투인터랙티브 소프트웨어"},
    "RBLX": {"corp": "Roblox Corp.", "ko": "로블록스"},
    "U": {"corp": "Unity Software", "ko": "유니티"},
    "JPM": {"corp": "JPMorgan Chase & Co.", "ko": "JP모건"},
    "GS": {"corp": "Goldman Sachs Group", "ko": "골드만삭스"},
    "MS": {"corp": "Morgan Stanley", "ko": "모건 스탠리"},
    "BAC": {"corp": "Bank of America Corp.", "ko": "뱅크오브아메리카"},
    "WFC": {"corp": "Wells Fargo & Co.", "ko": "웰스 파고"},
    "C": {"corp": "Citigroup Inc.", "ko": "씨티그룹"},
    "BLK": {"corp": "BlackRock Inc.", "ko": "블랙록"},
    "BX": {"corp": "Blackstone Inc.", "ko": "블랙스톤"},
    "KKR": {"corp": "KKR & Co.", "ko": "KKR"},
    "AXP": {"corp": "American Express Co.", "ko": "아메리칸 익스프레스"},
    "COF": {"corp": "Capital One Financial", "ko": "캐피탈 원"},
    "SCHW": {"corp": "Charles Schwab Corp.", "ko": "찰스 슈왑"},
    "USB": {"corp": "U.S. Bancorp", "ko": "US 뱅코프"},
    "PNC": {"corp": "PNC Financial Services", "ko": "PNC 파이낸셜"},
    "TFC": {"corp": "Truist Financial Corp.", "ko": "트루이스트"},
    "KEY": {"corp": "KeyCorp", "ko": "키코프"},
    "RF": {"corp": "Regions Financial Corp.", "ko": "리전스 파이낸셜"},
    "FITB": {"corp": "Fifth Third Bancorp", "ko": "피프스 서드 뱅코프"},
    "MTB": {"corp": "M&T Bank Corp.", "ko": "M&T 뱅크"},
    "CFG": {"corp": "Citizens Financial Group", "ko": "시티즌스 파이낸셜 그룹"},
    "HBAN": {"corp": "Huntington Bancshares", "ko": "헌팅턴 뱅크셰어즈"},
    "STT": {"corp": "State Street Corp.", "ko": "스테이트 스트리트"},
    "BK": {"corp": "Bank of New York Mellon", "ko": "뱅크 오브 뉴욕 멜론"},
    "NTRS": {"corp": "Northern Trust Corp.", "ko": "노던 트러스트"},
    "RJF": {"corp": "Raymond James Financial", "ko": "레이먼드 제임스"},
    "AMP": {"corp": "Ameriprise Financial", "ko": "아메리프라이즈 파이낸셜"},
    "TROW": {"corp": "T. Rowe Price Group", "ko": "티 로우 프라이스"},
    "BEN": {"corp": "Franklin Resources", "ko": "프랭클린 리소시스"},
    "IVZ": {"corp": "Invesco Ltd.", "ko": "인베스코"},
    "ICE": {"corp": "Intercontinental Exchange", "ko": "ICE"},
    "CME": {"corp": "CME Group Inc.", "ko": "CME그룹"},
    "CBOE": {"corp": "Cboe Global Markets", "ko": "Cboe 글로벌"},
    "NDAQ": {"corp": "Nasdaq Inc.", "ko": "나스닥"},
    "MCO": {"corp": "Moody's Corp.", "ko": "무디스"},
    "SPGI": {"corp": "S&P Global Inc.", "ko": "S&P 글로벌"},
    "MKTX": {"corp": "MarketAxess Holdings", "ko": "마켓액세스 홀딩스"},
    "MET": {"corp": "MetLife Inc.", "ko": "메트라이프"},
    "PRU": {"corp": "Prudential Financial", "ko": "프루덴셜"},
    "AFL": {"corp": "Aflac Inc.", "ko": "아플락"},
    "ALL": {"corp": "Allstate Corp.", "ko": "올스테이트"},
    "TRV": {"corp": "Travelers Companies", "ko": "트래블러스"},
    "CB": {"corp": "Chubb Ltd.", "ko": "처브"},
    "PGR": {"corp": "Progressive Corp.", "ko": "프로그레시브"},
    "HIG": {"corp": "Hartford Financial Services", "ko": "하트포드"},
    "AIG": {"corp": "American International Group", "ko": "AIG"},
    "MMC": {"corp": "Marsh & McLennan", "ko": "마쉬 앤 맥레넌"},
    "AON": {"corp": "Aon plc", "ko": "에이온"},
    "AJG": {"corp": "Arthur J. Gallagher & Co.", "ko": "아서 J 갤러거"},
    "WTW": {"corp": "Willis Towers Watson", "ko": "윌리스 타워스 왓슨"},
    "BRO": {"corp": "Brown & Brown Inc.", "ko": "브라운 앤 브라운"},
    "RE": {"corp": "Everest Re Group", "ko": "에버레스트 리 그룹"},
    "ACGL": {"corp": "Arch Capital Group", "ko": "아치 캐피탈"},
    "AIZ": {"corp": "Assurant Inc.", "ko": "어슈어런트"},
    "PFG": {"corp": "Principal Financial Group", "ko": "프린시펄 파이낸셜"},
    "GL": {"corp": "Globe Life Inc.", "ko": "글로브 라이프"},
    "CINF": {"corp": "Cincinnati Financial", "ko": "신시내티 파이낸셜"},
    "WRB": {"corp": "W.R. Berkley Corp.", "ko": "WR 버클리"},
    "V": {"corp": "Visa Inc.", "ko": "비자"},
    "MA": {"corp": "Mastercard Inc.", "ko": "마스터카드"},
    "PYPL": {"corp": "PayPal Holdings", "ko": "페이팔 홀딩스"},
    "SQ": {"corp": "Block Inc.", "ko": "블록(스퀘어)"},
    "AFRM": {"corp": "Affirm Holdings", "ko": "어펌"},
    "COIN": {"corp": "Coinbase Global", "ko": "코인베이스"},
    "CPAY": {"corp": "Corpay Inc.", "ko": "코페이"},
    "SYF": {"corp": "Synchrony Financial", "ko": "싱크로니 파이낸셜"},
    "DFS": {"corp": "Discover Financial Services", "ko": "디스커버 파이낸셜"},
    "RIVN": {"corp": "Rivian Automotive", "ko": "리비안"},
    "LCID": {"corp": "Lucid Group", "ko": "루시드"},
    "F": {"corp": "Ford Motor Co.", "ko": "포드"},
    "GM": {"corp": "General Motors Co.", "ko": "제너럴 모터스"},
    "STLA": {"corp": "Stellantis N.V.", "ko": "스텔란티스"},
    "APTV": {"corp": "Aptiv plc", "ko": "앱티브"},
    "BWA": {"corp": "BorgWarner Inc.", "ko": "보그워너"},
    "LEA": {"corp": "Lear Corp.", "ko": "리어"},
    "TM": {"corp": "Toyota Motor Corp.", "ko": "도요타"},
    "HMC": {"corp": "Honda Motor Co.", "ko": "혼다"},
    "NIO": {"corp": "NIO Inc.", "ko": "NIO"},
    "LI": {"corp": "Li Auto Inc.", "ko": "리오토"},
    "XPEV": {"corp": "XPeng Inc.", "ko": "샤오펑"},
    "KMX": {"corp": "CarMax Inc.", "ko": "카맥스"},
    "AN": {"corp": "AutoNation Inc.", "ko": "오토네이션"},
    "JNJ": {"corp": "Johnson & Johnson", "ko": "존슨앤존슨"},
    "PFE": {"corp": "Pfizer Inc.", "ko": "화이자"},
    "MRNA": {"corp": "Moderna Inc.", "ko": "모더나"},
    "ABBV": {"corp": "AbbVie Inc.", "ko": "애브비"},
    "LLY": {"corp": "Eli Lilly and Co.", "ko": "일라이릴리"},
    "BMY": {"corp": "Bristol-Myers Squibb", "ko": "브리스톨 마이어스 스퀴브"},
    "MRK": {"corp": "Merck & Co.", "ko": "머크앤드컴퍼니"},
    "GILD": {"corp": "Gilead Sciences", "ko": "길리어드 사이언스"},
    "REGN": {"corp": "Regeneron Pharmaceuticals", "ko": "리제네론 파마슈티컬스"},
    "BIIB": {"corp": "Biogen Inc.", "ko": "바이오젠"},
    "VRTX": {"corp": "Vertex Pharmaceuticals", "ko": "버텍스 파마슈티컬"},
    "AMGN": {"corp": "Amgen Inc.", "ko": "암젠"},
    "ISRG": {"corp": "Intuitive Surgical", "ko": "인튜이티브 서지컬"},
    "INCY": {"corp": "Incyte Corp.", "ko": "인사이트 코퍼레이션"},
    "ALNY": {"corp": "Alnylam Pharmaceuticals", "ko": "알닐람 파마슈티컬스"},
    "BMRN": {"corp": "BioMarin Pharmaceutical", "ko": "바이오마린"},
    "NBIX": {"corp": "Neurocrine Biosciences", "ko": "뉴로크린 바이오사이언스"},
    "SRPT": {"corp": "Sarepta Therapeutics", "ko": "사렙타 테라퓨틱스"},
    "RXRX": {"corp": "Recursion Pharmaceuticals", "ko": "리커전 파마슈티컬스"},
    "CRSP": {"corp": "CRISPR Therapeutics", "ko": "크리스퍼 테라퓨틱스"},
    "BEAM": {"corp": "Beam Therapeutics", "ko": "빔 테라퓨틱스"},
    "EDIT": {"corp": "Editas Medicine", "ko": "에디타스 메디신"},
    "ABT": {"corp": "Abbott Laboratories", "ko": "애보트 래버러토리스"},
    "MDT": {"corp": "Medtronic plc", "ko": "메드트로닉"},
    "BSX": {"corp": "Boston Scientific", "ko": "보스턴사이언티픽"},
    "EW": {"corp": "Edwards Lifesciences", "ko": "에드워즈라이프사이언시스"},
    "SYK": {"corp": "Stryker Corp.", "ko": "스트라이커"},
    "ZBH": {"corp": "Zimmer Biomet Holdings", "ko": "짐머 바이오메트"},
    "BAX": {"corp": "Baxter International", "ko": "박스터 인터내셔널"},
    "BDX": {"corp": "Becton Dickinson & Co.", "ko": "벡톤 디킨슨"},
    "DXCM": {"corp": "DexCom Inc.", "ko": "덱스컴"},
    "PODD": {"corp": "Insulet Corp.", "ko": "인슐렛"},
    "ALGN": {"corp": "Align Technology", "ko": "얼라인테크놀로지"},
    "IDXX": {"corp": "IDEXX Laboratories", "ko": "아이덱스 래버러토리스"},
    "MTD": {"corp": "Mettler-Toledo International", "ko": "메틀러-토레도 인터내셔널"},
    "WAT": {"corp": "Waters Corp.", "ko": "워터스 코퍼레이션"},
    "TMO": {"corp": "Thermo Fisher Scientific", "ko": "써모 피셔 사이언티픽"},
    "DHR": {"corp": "Danaher Corp.", "ko": "다나허"},
    "A": {"corp": "Agilent Technologies", "ko": "애질런트 테크놀로지스"},
    "RMD": {"corp": "ResMed Inc.", "ko": "레스메드"},
    "HOLX": {"corp": "Hologic Inc.", "ko": "홀로직"},
    "COO": {"corp": "Cooper Companies", "ko": "쿠퍼 컴퍼니스"},
    "WST": {"corp": "West Pharmaceutical Services", "ko": "웨스트 파마슈티컬"},
    "TECH": {"corp": "Bio-Techne Corp.", "ko": "바이오-테크네"},
    "STE": {"corp": "STERIS plc", "ko": "스테리스"},
    "RVTY": {"corp": "Revvity Inc.", "ko": "레브비티"},
    "CRL": {"corp": "Charles River Laboratories", "ko": "찰스 리버 래버러토리즈"},
    "ILMN": {"corp": "Illumina Inc.", "ko": "일루미나"},
    "IQV": {"corp": "IQVIA Holdings", "ko": "아이큐비아 홀딩스"},
    "VEEV": {"corp": "Veeva Systems", "ko": "비바 시스템즈"},
    "DVA": {"corp": "DaVita Inc.", "ko": "다비타"},
    "DGX": {"corp": "Quest Diagnostics", "ko": "퀘스트 다이아그노스틱스"},
    "LH": {"corp": "Labcorp Holdings", "ko": "랩코프 홀딩스"},
    "UNH": {"corp": "UnitedHealth Group", "ko": "유나이티드헬스그룹"},
    "HUM": {"corp": "Humana Inc.", "ko": "휴매너"},
    "CVS": {"corp": "CVS Health Corp.", "ko": "CVS 헬스"},
    "CI": {"corp": "Cigna Group", "ko": "시그나"},
    "ELV": {"corp": "Elevance Health", "ko": "엘레반스 헬스"},
    "MOH": {"corp": "Molina Healthcare", "ko": "몰리나 헬스케어"},
    "CNC": {"corp": "Centene Corp.", "ko": "센텐"},
    "HCA": {"corp": "HCA Healthcare", "ko": "HCA 홀딩스"},
    "UHS": {"corp": "Universal Health Services", "ko": "유니버셜 헬스 서비스"},
    "MCK": {"corp": "McKesson Corp.", "ko": "맥케슨"},
    "CAH": {"corp": "Cardinal Health", "ko": "카디널 헬스"},
    "XOM": {"corp": "Exxon Mobil Corp.", "ko": "엑슨모빌"},
    "CVX": {"corp": "Chevron Corp.", "ko": "셰브론"},
    "COP": {"corp": "ConocoPhillips", "ko": "코노코필립스"},
    "SLB": {"corp": "SLB (Schlumberger)", "ko": "슐럼버거"},
    "OXY": {"corp": "Occidental Petroleum", "ko": "옥시덴탈"},
    "EOG": {"corp": "EOG Resources", "ko": "EOG 리소시스"},
    "DVN": {"corp": "Devon Energy Corp.", "ko": "데본 에너지"},
    "FANG": {"corp": "Diamondback Energy", "ko": "다이아몬드백 에너지"},
    "MPC": {"corp": "Marathon Petroleum", "ko": "마라톤 페트롤륨"},
    "VLO": {"corp": "Valero Energy Corp.", "ko": "발레로 에너지"},
    "PSX": {"corp": "Phillips 66", "ko": "필립스 66"},
    "HAL": {"corp": "Halliburton Co.", "ko": "할리버튼"},
    "BKR": {"corp": "Baker Hughes Co.", "ko": "베이커 휴즈"},
    "HES": {"corp": "Hess Corp.", "ko": "헤스"},
    "APA": {"corp": "APA Corp.", "ko": "아파치"},
    "MRO": {"corp": "Marathon Oil Corp.", "ko": "마라톤 오일"},
    "CTRA": {"corp": "Coterra Energy", "ko": "코테라 에너지"},
    "LNG": {"corp": "Cheniere Energy", "ko": "셔니어 에너지"},
    "EQT": {"corp": "EQT Corp.", "ko": "EQT"},
    "AR": {"corp": "Antero Resources", "ko": "안테로 리소시스"},
    "KMI": {"corp": "Kinder Morgan", "ko": "킨더 모건"},
    "WMB": {"corp": "Williams Companies", "ko": "윌리엄스 컴퍼니스"},
    "OKE": {"corp": "ONEOK Inc.", "ko": "원오크"},
    "TRGP": {"corp": "Targa Resources", "ko": "타가 리소시즈"},
    "FSLR": {"corp": "First Solar Inc.", "ko": "퍼스트 솔라"},
    "ENPH": {"corp": "Enphase Energy", "ko": "인페이즈 에너지"},
    "CEG": {"corp": "Constellation Energy", "ko": "콘스텔레이션 에너지"},
    "VST": {"corp": "Vistra Corp.", "ko": "비스트라 에너지"},
    "NRG": {"corp": "NRG Energy", "ko": "NRG 에너지"},
    "FCX": {"corp": "Freeport-McMoRan Inc.", "ko": "프리포트 맥모란"},
    "NEM": {"corp": "Newmont Corp.", "ko": "뉴몬트 골드코프"},
    "NUE": {"corp": "Nucor Corp.", "ko": "뉴코"},
    "STLD": {"corp": "Steel Dynamics Inc.", "ko": "스틸 다이나믹스"},
    "VMC": {"corp": "Vulcan Materials Co.", "ko": "벌칸 머티리얼"},
    "MLM": {"corp": "Martin Marietta Materials", "ko": "마틴 마리에타"},
    "LIN": {"corp": "Linde plc", "ko": "린드"},
    "APD": {"corp": "Air Products & Chemicals", "ko": "에어 프로덕츠"},
    "ECL": {"corp": "Ecolab Inc.", "ko": "에코랩"},
    "SHW": {"corp": "Sherwin-Williams Co.", "ko": "셔윈 윌리엄스"},
    "PPG": {"corp": "PPG Industries", "ko": "PPG 인더스트리즈"},
    "DD": {"corp": "DuPont de Nemours", "ko": "듀폰"},
    "DOW": {"corp": "Dow Inc.", "ko": "다우"},
    "LYB": {"corp": "LyondellBasell Industries", "ko": "리온델바셀 인더스트리즈"},
    "EMN": {"corp": "Eastman Chemical Co.", "ko": "이스트만케미컬"},
    "CE": {"corp": "Celanese Corp.", "ko": "셀라니즈"},
    "CF": {"corp": "CF Industries Holdings", "ko": "CF 인더스트리"},
    "MOS": {"corp": "Mosaic Co.", "ko": "모자이크"},
    "FMC": {"corp": "FMC Corp.", "ko": "FMC 코퍼레이션"},
    "ALB": {"corp": "Albemarle Corp.", "ko": "알버말"},
    "BLL": {"corp": "Ball Corp.", "ko": "볼 코퍼레이션"},
    "AVY": {"corp": "Avery Dennison Corp.", "ko": "에이버리 데니슨"},
    "PKG": {"corp": "Packaging Corp. of America", "ko": "패키징 코퍼레이션"},
    "IP": {"corp": "International Paper Co.", "ko": "인터내셔널 페이퍼"},
    "GLW": {"corp": "Corning Inc.", "ko": "코닝"},
    "NVT": {"corp": "nVent Electric", "ko": "엔벤트 일렉트릭"},
    "AMCR": {"corp": "Amcor plc", "ko": "암코"},
    "WMT": {"corp": "Walmart Inc.", "ko": "월마트"},
    "TGT": {"corp": "Target Corp.", "ko": "타깃"},
    "COST": {"corp": "Costco Wholesale", "ko": "코스트코"},
    "HD": {"corp": "Home Depot Inc.", "ko": "홈디포"},
    "LOW": {"corp": "Lowe's Companies", "ko": "로우스"},
    "EBAY": {"corp": "eBay Inc.", "ko": "이베이"},
    "ETSY": {"corp": "Etsy Inc.", "ko": "엣시"},
    "CHWY": {"corp": "Chewy Inc.", "ko": "츄이"},
    "BBY": {"corp": "Best Buy Co.", "ko": "베스트바이"},
    "DG": {"corp": "Dollar General Corp.", "ko": "달러 제너럴"},
    "DLTR": {"corp": "Dollar Tree Inc.", "ko": "달러트리"},
    "KR": {"corp": "Kroger Co.", "ko": "크로거"},
    "AZO": {"corp": "AutoZone Inc.", "ko": "오토존"},
    "ORLY": {"corp": "O'Reilly Automotive", "ko": "오릴리 오토모티브"},
    "ROST": {"corp": "Ross Stores Inc.", "ko": "로스 스토어스"},
    "TJX": {"corp": "TJX Companies", "ko": "TJX 컴퍼니"},
    "TSCO": {"corp": "Tractor Supply Co.", "ko": "트랙터 서플라이"},
    "NKE": {"corp": "Nike Inc.", "ko": "나이키"},
    "LULU": {"corp": "Lululemon Athletica", "ko": "룰루레몬"},
    "ULTA": {"corp": "Ulta Beauty Inc.", "ko": "울타 뷰티"},
    "EL": {"corp": "Estee Lauder Companies", "ko": "에스티 로더"},
    "TPR": {"corp": "Tapestry Inc.", "ko": "태피스트리"},
    "RL": {"corp": "Ralph Lauren Corp.", "ko": "랄프로렌"},
    "PVH": {"corp": "PVH Corp.", "ko": "PVH 코퍼레이션"},
    "UAA": {"corp": "Under Armour (A)", "ko": "언더아머 A"},
    "UA": {"corp": "Under Armour (C)", "ko": "언더아머 C"},
    "ANF": {"corp": "Abercrombie & Fitch", "ko": "애버크롬비 앤 피치"},
    "DECK": {"corp": "Deckers Outdoor Corp.", "ko": "덱커 아웃도어"},
    "BLDR": {"corp": "Builders FirstSource", "ko": "빌더스 퍼스트소스"},
    "PHM": {"corp": "PulteGroup Inc.", "ko": "펄티 그룹"},
    "LEN": {"corp": "Lennar Corp.", "ko": "레나"},
    "DHI": {"corp": "D.R. Horton Inc.", "ko": "DR호튼"},
    "NVR": {"corp": "NVR Inc.", "ko": "NVR"},
    "TOL": {"corp": "Toll Brothers Inc.", "ko": "톨 브라더스"},
    "SIG": {"corp": "Signet Jewelers", "ko": "시그넷 주얼러스"},
    "KO": {"corp": "The Coca-Cola Co.", "ko": "코카콜라"},
    "PEP": {"corp": "PepsiCo Inc.", "ko": "펩시코"},
    "MCD": {"corp": "McDonald's Corp.", "ko": "맥도날드"},
    "SBUX": {"corp": "Starbucks Corp.", "ko": "스타벅스"},
    "YUM": {"corp": "Yum! Brands", "ko": "얌브랜드"},
    "CMG": {"corp": "Chipotle Mexican Grill", "ko": "치폴레"},
    "DPZ": {"corp": "Domino's Pizza", "ko": "도미노피자"},
    "DRI": {"corp": "Darden Restaurants", "ko": "다든 레스토랑"},
    "PG": {"corp": "Procter & Gamble Co.", "ko": "P&G"},
    "CL": {"corp": "Colgate-Palmolive Co.", "ko": "콜게이트-팜올리브"},
    "KMB": {"corp": "Kimberly-Clark Corp.", "ko": "킴벌리클라크"},
    "CHD": {"corp": "Church & Dwight Co.", "ko": "처치앤드와이트"},
    "CLX": {"corp": "Clorox Co.", "ko": "클로락스"},
    "MDLZ": {"corp": "Mondelez International", "ko": "몬델리즈 인터내셔널"},
    "GIS": {"corp": "General Mills Inc.", "ko": "제너럴 밀스"},
    "KHC": {"corp": "Kraft Heinz Co.", "ko": "크래프트 하인즈"},
    "CPB": {"corp": "Campbell's Co.", "ko": "캠벨"},
    "HRL": {"corp": "Hormel Foods Corp.", "ko": "호멜"},
    "MKC": {"corp": "McCormick & Co.", "ko": "맥코믹"},
    "SJM": {"corp": "J.M. Smucker Co.", "ko": "JM 스머커"},
    "TSN": {"corp": "Tyson Foods Inc.", "ko": "타이슨 푸드"},
    "ADM": {"corp": "Archer-Daniels-Midland", "ko": "ADM"},
    "BG": {"corp": "Bunge Global SA", "ko": "번지"},
    "CAG": {"corp": "Conagra Brands", "ko": "콘아그라 브랜즈"},
    "HSY": {"corp": "Hershey Co.", "ko": "허쉬"},
    "MNST": {"corp": "Monster Beverage Corp.", "ko": "몬스터 베버리지"},
    "STZ": {"corp": "Constellation Brands", "ko": "컨스텔레이션 브랜드"},
    "TAP": {"corp": "Molson Coors Beverage", "ko": "몰슨 쿠어스 양조"},
    "CELH": {"corp": "Celsius Holdings", "ko": "셀시우스 홀딩스"},
    "KDP": {"corp": "Keurig Dr Pepper", "ko": "큐리그 닥터 페퍼"},
    "PM": {"corp": "Philip Morris International", "ko": "필립 모리스"},
    "MO": {"corp": "Altria Group", "ko": "알트리아 그룹"},
    "ABNB": {"corp": "Airbnb Inc.", "ko": "에어비앤비"},
    "BKNG": {"corp": "Booking Holdings", "ko": "부킹홀딩스"},
    "EXPE": {"corp": "Expedia Group", "ko": "익스피디아"},
    "MAR": {"corp": "Marriott International", "ko": "메리어트인터내셔널"},
    "HLT": {"corp": "Hilton Worldwide", "ko": "힐튼 월드와이드"},
    "H": {"corp": "Hyatt Hotels Corp.", "ko": "하얏트"},
    "HST": {"corp": "Host Hotels & Resorts", "ko": "호스트 호텔 앤 리조트"},
    "MGM": {"corp": "MGM Resorts International", "ko": "MGM 리조트 인터내셔널"},
    "WYNN": {"corp": "Wynn Resorts Ltd.", "ko": "윈 리조트"},
    "LVS": {"corp": "Las Vegas Sands Corp.", "ko": "라스베가스 샌즈"},
    "CZR": {"corp": "Caesars Entertainment", "ko": "시저스 엔터테인먼트"},
    "RCL": {"corp": "Royal Caribbean Cruises", "ko": "로얄 캐리비안"},
    "CCL": {"corp": "Carnival Corp.", "ko": "카니발"},
    "NCLH": {"corp": "Norwegian Cruise Line", "ko": "노르웨이안 크루즈 홀딩스"},
    "DAL": {"corp": "Delta Air Lines", "ko": "델타항공"},
    "UAL": {"corp": "United Airlines Holdings", "ko": "유나이티드 항공"},
    "AAL": {"corp": "American Airlines Group", "ko": "아메리칸 항공"},
    "LUV": {"corp": "Southwest Airlines", "ko": "사우스웨스트 항공"},
    "BA": {"corp": "Boeing Co.", "ko": "보잉"},
    "LMT": {"corp": "Lockheed Martin Corp.", "ko": "록히드 마틴"},
    "RTX": {"corp": "RTX Corp.", "ko": "RTX"},
    "NOC": {"corp": "Northrop Grumman", "ko": "노스롭 그루먼"},
    "GD": {"corp": "General Dynamics", "ko": "제너럴 다이내믹스"},
    "LHX": {"corp": "L3Harris Technologies", "ko": "L3해리스 테크놀로지스"},
    "HII": {"corp": "Huntington Ingalls Industries", "ko": "헌팅턴 잉걸스"},
    "TDY": {"corp": "Teledyne Technologies", "ko": "텔레다인 테크"},
    "HEI": {"corp": "HEICO Corp.", "ko": "히코"},
    "HWM": {"corp": "Howmet Aerospace", "ko": "하우멧 에어로스페이스"},
    "TDG": {"corp": "TransDigm Group", "ko": "트랜스다임 그룹"},
    "AXON": {"corp": "Axon Enterprise", "ko": "액슨 엔터프라이즈"},
    "KTOS": {"corp": "Kratos Defense & Security", "ko": "크라토스 디펜스"},
    "LDOS": {"corp": "Leidos Holdings", "ko": "레이도스"},
    "BAH": {"corp": "Booz Allen Hamilton", "ko": "부즈 앨런 해밀턴"},
    "CAT": {"corp": "Caterpillar Inc.", "ko": "캐터필러"},
    "DE": {"corp": "Deere & Co.", "ko": "디어"},
    "HON": {"corp": "Honeywell International", "ko": "하니웰"},
    "MMM": {"corp": "3M Co.", "ko": "3M"},
    "GE": {"corp": "GE Aerospace", "ko": "GE 에어로스페이스"},
    "GEV": {"corp": "GE Vernova LLC", "ko": "GE 버노바"},
    "GEHC": {"corp": "GE HealthCare Technologies", "ko": "GE 헬스케어"},
    "ETN": {"corp": "Eaton Corp.", "ko": "이튼"},
    "EMR": {"corp": "Emerson Electric Co.", "ko": "에머슨 일렉트릭"},
    "ITW": {"corp": "Illinois Tool Works", "ko": "일리노이 툴 웍스"},
    "PH": {"corp": "Parker Hannifin Corp.", "ko": "파카 하니핀"},
    "ROK": {"corp": "Rockwell Automation", "ko": "로크웰 오토메이션"},
    "AME": {"corp": "AMETEK Inc.", "ko": "아메텍"},
    "DOV": {"corp": "Dover Corp.", "ko": "도버"},
    "IR": {"corp": "Ingersoll Rand Inc.", "ko": "잉가솔랜드"},
    "TT": {"corp": "Trane Technologies", "ko": "트레인 테크놀로지"},
    "JCI": {"corp": "Johnson Controls International", "ko": "존슨콘트롤즈"},
    "OTIS": {"corp": "Otis Worldwide Corp.", "ko": "오티스 월드와이드"},
    "CARR": {"corp": "Carrier Global Corp.", "ko": "캐리어"},
    "GWW": {"corp": "W.W. Grainger Inc.", "ko": "WW 그레인저"},
    "FAST": {"corp": "Fastenal Co.", "ko": "패스널"},
    "NDSN": {"corp": "Nordson Corp.", "ko": "노드슨"},
    "XYL": {"corp": "Xylem Inc.", "ko": "자일럼"},
    "PNR": {"corp": "Pentair plc", "ko": "펜테어"},
    "GNRC": {"corp": "Generac Holdings", "ko": "제너락"},
    "AOS": {"corp": "A.O. Smith Corp.", "ko": "A.O 스미스"},
    "SWK": {"corp": "Stanley Black & Decker", "ko": "스탠리 블랙 앤 데커"},
    "MAS": {"corp": "Masco Corp.", "ko": "마스코"},
    "HUBB": {"corp": "Hubbell Inc.", "ko": "허벨"},
    "CMI": {"corp": "Cummins Inc.", "ko": "커민스"},
    "TEL": {"corp": "TE Connectivity", "ko": "TE 커넥티비티"},
    "APH": {"corp": "Amphenol Corp.", "ko": "암페놀"},
    "WAB": {"corp": "Wabtec Corp.", "ko": "웨이스팅하우스 에어브레이크"},
    "PWR": {"corp": "Quanta Services", "ko": "콴타 서비시즈"},
    "FTV": {"corp": "Fortive Corp.", "ko": "포티브 코퍼레이션"},
    "KEYS": {"corp": "Keysight Technologies", "ko": "키사이트 테크놀로지"},
    "ZBRA": {"corp": "Zebra Technologies", "ko": "지브라 테크"},
    "TXT": {"corp": "Textron Inc.", "ko": "텍스트론"},
    "T": {"corp": "AT&T Inc.", "ko": "AT&T"},
    "VZ": {"corp": "Verizon Communications", "ko": "버라이즌 커뮤니케이션"},
    "TMUS": {"corp": "T-Mobile US Inc.", "ko": "티모바일"},
    "CHTR": {"corp": "Charter Communications", "ko": "차터커뮤니케이션"},
    "LUMN": {"corp": "Lumen Technologies", "ko": "루멘 테크놀로지"},
    "MSI": {"corp": "Motorola Solutions", "ko": "모토롤라 솔루션"},
    "UPS": {"corp": "United Parcel Service", "ko": "유나이티드파슬서비스"},
    "FDX": {"corp": "FedEx Corp.", "ko": "페덱스"},
    "UNP": {"corp": "Union Pacific Corp.", "ko": "유니온 퍼시픽"},
    "CSX": {"corp": "CSX Corp.", "ko": "CSX"},
    "NSC": {"corp": "Norfolk Southern Corp.", "ko": "노퍽 서던"},
    "CP": {"corp": "Canadian Pacific Kansas City", "ko": "캐나다 퍼시픽 캔자스 시티"},
    "CNI": {"corp": "Canadian National Railway", "ko": "캐나다 내셔널 철도"},
    "JBHT": {"corp": "J.B. Hunt Transport Services", "ko": "J.B 헌트트랜스포트서비스"},
    "ODFL": {"corp": "Old Dominion Freight Line", "ko": "올드 도미니언 프레이트 라인"},
    "CHRW": {"corp": "C.H. Robinson Worldwide", "ko": "C.H.로빈슨"},
    "EXPD": {"corp": "Expeditors International", "ko": "익스피다이터스"},
    "PCAR": {"corp": "PACCAR Inc.", "ko": "파카"},
    "CPRT": {"corp": "Copart Inc.", "ko": "코파츠"},
    "UBER": {"corp": "Uber Technologies", "ko": "우버 테크놀로지스"},
    "LYFT": {"corp": "Lyft Inc.", "ko": "리프트"},
    "DASH": {"corp": "DoorDash Inc.", "ko": "도어대시"},
    "WM": {"corp": "Waste Management Inc.", "ko": "웨이스트 매니지먼트"},
    "RSG": {"corp": "Republic Services Inc.", "ko": "리퍼블릭 서비스"},
    "URI": {"corp": "United Rentals Inc.", "ko": "유나이티드렌탈"},
    "CTAS": {"corp": "Cintas Corp.", "ko": "신타스"},
    "PLD": {"corp": "Prologis Inc.", "ko": "프로로지스"},
    "AMT": {"corp": "American Tower Corp.", "ko": "아메리칸 타워"},
    "EQIX": {"corp": "Equinix Inc.", "ko": "에퀴닉스"},
    "CCI": {"corp": "Crown Castle Inc.", "ko": "크라운 캐슬"},
    "DLR": {"corp": "Digital Realty Trust", "ko": "디지털리얼"},
    "O": {"corp": "Realty Income Corp.", "ko": "리얼티인컴"},
    "VICI": {"corp": "VICI Properties", "ko": "VICI 프로퍼티즈"},
    "WELL": {"corp": "Welltower Inc.", "ko": "웰타워"},
    "VTR": {"corp": "Ventas Inc.", "ko": "벤타스"},
    "SPG": {"corp": "Simon Property Group", "ko": "사이먼 프로퍼티"},
    "PSA": {"corp": "Public Storage", "ko": "퍼블릭 스토리지"},
    "EXR": {"corp": "Extra Space Storage", "ko": "엑스트라 스페이스 스토리지"},
    "AVB": {"corp": "AvalonBay Communities", "ko": "아발론베이"},
    "EQR": {"corp": "Equity Residential", "ko": "에쿼티 레지덴셜"},
    "MAA": {"corp": "Mid-America Apartment", "ko": "미드아메리카 아파트"},
    "CPT": {"corp": "Camden Property Trust", "ko": "캠든 프로퍼티"},
    "KIM": {"corp": "Kimco Realty Corp.", "ko": "킴코 리얼티"},
    "REG": {"corp": "Regency Centers Corp.", "ko": "리전시 센터"},
    "ARE": {"corp": "Alexandria Real Estate Equities", "ko": "알렉산드리아 리얼 에스테이트"},
    "SBAC": {"corp": "SBA Communications Corp.", "ko": "SBA커뮤니케이션"},
    "IRM": {"corp": "Iron Mountain Inc.", "ko": "아이언마운틴"},
    "INVH": {"corp": "Invitation Homes", "ko": "인비테이션 홈스"},
    "AMH": {"corp": "American Homes 4 Rent", "ko": "아메리칸 홈스4렌트"},
    "CSGP": {"corp": "CoStar Group", "ko": "코스타 그룹"},
    "DOC": {"corp": "Healthpeak Properties", "ko": "헬스픽 프로퍼티"},
    "FRT": {"corp": "Federal Realty Investment Trust", "ko": "페더럴 리얼티"},
    "ESS": {"corp": "Essex Property Trust", "ko": "에섹스 프로퍼티 트러스트"},
    "NEE": {"corp": "NextEra Energy", "ko": "넥스테라"},
    "DUK": {"corp": "Duke Energy Corp.", "ko": "듀크 에너지"},
    "SO": {"corp": "Southern Co.", "ko": "서던 컴퍼니"},
    "D": {"corp": "Dominion Energy", "ko": "도미니언 에너지"},
    "AEP": {"corp": "American Electric Power", "ko": "아메리칸 일렉트릭 파워"},
    "EXC": {"corp": "Exelon Corp.", "ko": "엑셀론"},
    "SRE": {"corp": "Sempra Energy", "ko": "셈프라 에너지"},
    "PCG": {"corp": "PG&E Corp.", "ko": "PG&E"},
    "XEL": {"corp": "Xcel Energy Inc.", "ko": "엑셀 에너지"},
    "ED": {"corp": "Consolidated Edison", "ko": "콘 에디슨"},
    "WEC": {"corp": "WEC Energy Group", "ko": "WEC 에너지그룹"},
    "DTE": {"corp": "DTE Energy Co.", "ko": "DTE 에너지"},
    "ETR": {"corp": "Entergy Corp.", "ko": "엔터지"},
    "EIX": {"corp": "Edison International", "ko": "에디슨 인터내셔널"},
    "AEE": {"corp": "Ameren Corp.", "ko": "애머렌"},
    "PPL": {"corp": "PPL Corp.", "ko": "PPL 코퍼레이션"},
    "PEG": {"corp": "Public Service Enterprise Group", "ko": "퍼블릭 서비스 엔터프라이즈"},
    "FE": {"corp": "FirstEnergy Corp.", "ko": "퍼스트에너지"},
    "CNP": {"corp": "CenterPoint Energy", "ko": "센터포인트 에너지"},
    "NI": {"corp": "NiSource Inc.", "ko": "니소스"},
    "ATO": {"corp": "Atmos Energy Corp.", "ko": "아토모스 에너지"},
    "LNT": {"corp": "Alliant Energy Corp.", "ko": "얼라이언트 에너지"},
    "EVRG": {"corp": "Evergy Inc.", "ko": "에버지"},
    "PNW": {"corp": "Pinnacle West Capital", "ko": "피나클 웨스트"},
    "AWK": {"corp": "American Water Works", "ko": "아메리칸워터웍스"},
    "AES": {"corp": "AES Corp.", "ko": "AES"},
    "J": {"corp": "Jacobs Solutions", "ko": "제이콥스 엔지니어링"},
    "FLR": {"corp": "Fluor Corp.", "ko": "플루어"},
    "MTZ": {"corp": "MasTec Inc.", "ko": "마스텍"},
    "CBRE": {"corp": "CBRE Group", "ko": "CBRE"},
    "GRMN": {"corp": "Garmin Ltd.", "ko": "가민"},
    "GPC": {"corp": "Genuine Parts Co.", "ko": "제뉴인 파츠"},
    "SNA": {"corp": "Snap-on Inc.", "ko": "스냅온"},
    "OMC": {"corp": "Omnicom Group", "ko": "옴니콤"},
    "IPG": {"corp": "Interpublic Group", "ko": "인터퍼블릭"},
    "HAS": {"corp": "Hasbro Inc.", "ko": "해즈브로"},
    "MAT": {"corp": "Mattel Inc.", "ko": "마텔"},
    "BABA": {"corp": "Alibaba Group", "ko": "알리바바"},
    "JD": {"corp": "JD.com Inc.", "ko": "징둥닷컴"},
    "PDD": {"corp": "PDD Holdings (Pinduoduo)", "ko": "핀둬둬"},
    "BIDU": {"corp": "Baidu Inc.", "ko": "바이두"},
    "BILI": {"corp": "Bilibili Inc.", "ko": "빌리빌리"},
    "TCOM": {"corp": "Trip.com Group", "ko": "트립닷컴"},
    "TME": {"corp": "Tencent Music Entertainment", "ko": "텐센트 뮤직"},
    "IQ": {"corp": "iQIYI Inc.", "ko": "아이치이"},
    "VIPS": {"corp": "Vipshop Holdings", "ko": "비프샵"},
    "SKM": {"corp": "SK Telecom Co.", "ko": "SK텔레콤"},
    "KT": {"corp": "KT Corp.", "ko": "KT"},
    "KEP": {"corp": "Korea Electric Power", "ko": "한국전력"},
    "KB": {"corp": "KB Financial Group", "ko": "KB금융"},
    "SHG": {"corp": "Shinhan Financial Group", "ko": "신한금융"},
    "WF": {"corp": "Woori Financial Group", "ko": "우리금융"},
    "HDB": {"corp": "HDFC Bank (India ADR)", "ko": "HDFC 뱅크"},
    "NVO": {"corp": "Novo Nordisk A/S", "ko": "노보 노디스크"},
    "SONY": {"corp": "Sony Group Corp.", "ko": "소니"},
    "SAP": {"corp": "SAP SE", "ko": "SAP"},
    "AZN": {"corp": "AstraZeneca plc", "ko": "아스트라제네카"},
    "GSK": {"corp": "GSK plc", "ko": "GSK"},
    "SE": {"corp": "Sea Ltd.", "ko": "씨 리미티드"},
    "MELI": {"corp": "MercadoLibre Inc.", "ko": "메르카도리브레"},
    "GRAB": {"corp": "Grab Holdings", "ko": "그랩"},
    "VALE": {"corp": "Vale S.A.", "ko": "발레"},
    "PBR": {"corp": "Petrobras", "ko": "페트로브라스"},
    "ITUB": {"corp": "Itau Unibanco", "ko": "이타우 우니방코"},
    "ERJ": {"corp": "Embraer S.A.", "ko": "엠브라에르"},
}


# ── 4. 일반주식 필터 ──────────────────────────────────────────────
def is_common_stock(ticker: str) -> bool:
    if len(ticker) > 5:
        return False
    if re.search(r"[^A-Z.]", ticker):
        return False
    if ticker.endswith(("W", "WS", "WT", "WI", "R", "U", "Z")):
        return False
    return True


# ── 5. 최종 목록 구성 ─────────────────────────────────────────────
final: dict[str, dict[str, str]] = {}
for t in sorted(valid_tickers):
    if not is_common_stock(t):
        continue
    if t in sec_map:
        corp = sec_map[t]
    elif t in KO_MAP:
        corp = KO_MAP[t]["corp"]
    else:
        continue
    ko = KO_MAP[t]["ko"] if t in KO_MAP else corp
    final[t] = {"corp": corp, "ko": ko}

print(f"최종 티커 수: {len(final)}")
ko_count = sum(1 for v in final.values() if any(ord(c) > 127 for c in v["ko"]))
print(f"한국어 이름: {ko_count}개 / 영어 이름: {len(final) - ko_count}개")

# ── 6. ticker_names.py 생성 ───────────────────────────────────────
out_path = os.path.join(os.path.dirname(__file__), "..", "app", "services", "ticker_names.py")
out_path = os.path.normpath(out_path)

lines = [
    '"""',
    "미국 주식 티커 → 회사명 매핑 (영문 + 한국어)",
    "메모리 dict 조회 방식 — DB 추가 쿼리 없음",
    "한국어 이름이 없는 종목은 영문 회사명을 그대로 사용",
    '"""',
    "",
    "TICKER_NAMES: dict[str, dict[str, str]] = {",
]

for t, v in sorted(final.items()):
    corp = v["corp"].replace("\\", "").replace('"', '\\"')
    ko = v["ko"].replace("\\", "").replace('"', '\\"')
    lines.append(f'    "{t}": {{"corp": "{corp}", "ko": "{ko}"}},')

lines += [
    "}",
    "",
    "",
    "def get_ticker_name(ticker: str) -> dict[str, str] | None:",
    '    """티커 → {"corp": ..., "ko": ...} 반환. 없으면 None."""',
    "    return TICKER_NAMES.get(ticker.upper())",
    "",
    "",
    "def enrich_tickers(tickers: list[str]) -> list[dict[str, str]]:",
    '    """',
    "    티커 리스트 → ticker_names 리스트 반환.",
    "    매핑 없는 티커는 corp/ko를 ticker 값으로 채워서 포함.",
    '    """',
    "    result = []",
    "    for t in tickers:",
    "        name = get_ticker_name(t)",
    "        if name:",
    '            result.append({"ticker": t, **name})',
    "        else:",
    '            result.append({"ticker": t, "corp": t, "ko": t})',
    "    return result",
    "",
    "",
    "def search_tickers(query: str) -> list[str]:",
    '    """',
    "    한국어/영문 회사명으로 티커 검색.",
    "    query가 포함된 모든 티커 반환.",
    '    예: "애플" → ["AAPL"], "apple" → ["AAPL"]',
    '    """',
    "    q = query.strip().lower()",
    "    if not q:",
    "        return []",
    "    return [",
    "        ticker",
    "        for ticker, names in TICKER_NAMES.items()",
    '        if q in names["ko"].lower() or q in names["corp"].lower() or q in ticker.lower()',
    "    ]",
    "",
    "",
    "# /tickers 엔드포인트용 정적 응답 — 앱 시작 시 한 번만 빌드",
    "TICKER_LIST: list[dict[str, str]] = [",
    '    {"ticker": ticker, **names}',
    "    for ticker, names in TICKER_NAMES.items()",
    "]",
    "",
]

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

size = os.path.getsize(out_path)
print(f"저장 완료: {out_path}")
print(f"파일 크기: {size / 1024:.1f} KB")
